:jacoco: https://github.com/jacoco/jacoco

= What's Next

This just lists a few things that *may* happen in the future in no particular order. I'm working on this as times permits... &#x1f600;

== Quarkus/JAX-RS support

October 25

this is a two part thing

1. openapi-processor-jaxrs, this probably needs a few internal changes because the mapping is not described by a single annotation as with Spring or Micronaut.

2. a quarkus extension

== inline name mappings

October 24

the processor automatically generates names based on the yaml/json path for inline types (so they are unique). May be nice to map the generated name to a nicer name.

== autodetect unused mappings

October 24

the processor could detect which mappings are not used at all and report them to remove noise from the `mapping.yaml`

== internal OpenAPI parser

October 24

- native compilation

it is possible, don't know yet how to run native test, compiling tests as native image fails.


== json schema validator

May 24

- internal refactoring to separate validator code by draft version
- native compilation
