:jacoco: https://github.com/jacoco/jacoco

= What's Next

This just lists a few things that are planned for the future in no particular order. I'm working on this as times permits... &#x1f600;

at the moment there is nothing worth mentioning on this list.

== json schema validator

**added in 2023.4**

I made some progress on the json-schema-validator. draft 2019-09 and draft 2020-12 are nearly done. The validator is able to create the standard JSON schema output format. Validation of OpenAPI 3.0 is already using it.

2020-12 is required to validate OpenAPI 3.1. documents.

== internal OpenAPI 3.1

**added in 2023.4**

Add validation for OpenAPI 3.1 parser.


== annotation processor

**dropped**

unfortunately openapi-processor can't run as annotation processor. The problem is simply to detect when processing is necessary.

link:https://github.com/openapi-processor/openapi-processor-spring/pull/145[spring annotation processor prototype], link:https://github.com/openapi-processor/openapi-processor-core/pull/100[core annotation processor prototype]

Run openapi-processor as an annotation processor. This should make it easier to integrate openapi-processor into a build without the need of a plugin for the build tool.

I will probably try to support both for a while, i.e. make it run as annotation processor or via the plugins.
